#!/bin/sh
# Make the output files for each test

if [ ! -f build/comp ]
then echo "Need to build comp first!"; exit 1
fi

test_dir="test/10_for_loops"

for i in test/10_for_loops/input*
do if [ ! -f "out.${i##*/}" ]
   then
     ./build/comp $i 
     cc -o output output.s
     ./output > test/10_for_loops/out.${i##*/}
     rm -f output output.s
   fi
done
