#!/bin/sh
# Make the output files for each test

if [ ! -f build/comp ]
then echo "Need to build comp first!"; exit 1
fi

test_dir="test/13_functions_pt2"

for i in test/13_functions_pt2/input*
do if [ ! -f "out.${i##*/}" ]
   then
     ./build/comp $i 
     cc -o output output.s src/lib/print.c
     ./output > test/13_functions_pt2/out.${i##*/}
     rm -f output output.s
   fi
done
