#!/bin/sh
# Make the output files for each test

if [ ! -f build/comp ]
then echo "Need to build comp first!"; exit 1
fi

for i in test/09_while_statement/input*
do if [ ! -f "out.${i##*/}" ]
   then
     ./build/comp $i 
     cc -o output output.s
     ./output > test/09_while_statement/out.${i##*/}
     rm -f output output.s
   fi
done
